application: grimpuis
version: 1
api_version: 1
runtime: python

derived_file_type:
- python_precompiled

handlers:

- url: /_ah/stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py
  login: admin
 
## Comment these out because they depend on web2py using the application name in the URL
#- url: /(?P<a>.+?)/static/(?P<b>.+)
#  static_files: applications/\1/static/\2
#  upload: applications/(.+?)/static/(.+)
#  secure: optional
#  expiration: "90d"

### This one should work with the web2py routes.py which removes the application name (/init) from URLs
- url: /static/(?P<s>.+)
  static_files: applications/init/static/\1
  upload: applications/init/static/(.+)
  secure: optional
  expiration: "90d"
  
- url: /_ah/admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin
 
- url: /_ah/queue/default
  script: gaehandler.py
  login: admin

- url: .*
  script: gaehandler.py  
  secure: optional

admin_console:
  pages:
  - name: Appstats
    url: /_ah/stats
   
skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 ((admin|examples|welcome)\.tar)|
 (applications/(admin|examples|books|crm|isup|t3|welcome)/.*)|
 (applications/.*?/databases/.*) |
 (applications/.*?/errors/.*)|
 (applications/.*?/cache/.*)|
 (applications/.*?/sessions/.*)|
 )$
